In [1]:
import numpy as np
from sklearn.cluster import KMeans

In [6]:
def kmeans(X, k):
    """Creating a function that performs k-means clustering
    on a numerical NumPy array X that returns a tuple where
    centroids is a 2D array of shape containing the cluster
    centroids, and labels is a 1D array of shape containing
    the index of the assigned cluster for each row of X."""
    
    # Initialize and fit the Scikit-Learn KMeans model
    model = KMeans(n_clusters=k, n_init='auto', random_state=42)
    model.fit(X)
    
    # Extracting the centroids and labels as NumPy arrays
    centroids = model.cluster_centers_
    labels = model.labels_
    
    return centroids, labels

In [3]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
centroids, labels = kmeans(X, k=3)

In [8]:
print("Centroids:\n", centroids)
print("Labels:", labels)

Centroids:
 [[4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]]
Labels: [2 0 1]


In [10]:
kmeans(X, 3)

(array([[4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.]]),
 array([2, 0, 1], dtype=int32))