In [12]:
pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
  Using cached pyparsing-3.2.5-py3-none-any.whl.metadata (5.0 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -------------------------------- ------- 6.6/8.1 MB 35.5 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 32.6 MB/s  0:00:00
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 37.5 MB/s  0:00:00
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Using cached pyparsing-3.2.5-py3-none-any.whl (113 kB)



  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import numpy as np
from sklearn.cluster import KMeans
import seaborn as sns
import pandas as pd

In [6]:
def kmeans(X, k):
    """Creating a function that performs k-means clustering
    on a numerical NumPy array X that returns a tuple where
    centroids is a 2D array of shape containing the cluster
    centroids, and labels is a 1D array of shape containing
    the index of the assigned cluster for each row of X."""
    
    # Initialize and fit the Scikit-Learn KMeans model
    model = KMeans(n_clusters=k, n_init='auto', random_state=42)
    model.fit(X)
    
    # Extracting the centroids and labels as NumPy arrays
    centroids = model.cluster_centers_
    labels = model.labels_
    
    return centroids, labels

In [3]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
centroids, labels = kmeans(X, k=3)

In [8]:
print("Centroids:\n", centroids)
print("Labels:", labels)

Centroids:
 [[4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]]
Labels: [2 0 1]


In [10]:
kmeans(X, 3)

(array([[4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.]]),
 array([2, 0, 1], dtype=int32))